sonar.verbose=true
sonar.projectKey=nithinkrc-2026_Firstscan
sonar.organization=nithinkrc-2026
sonar.projectName=Firstscan
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
