sonar.verbose=true
sonar.projectKey=voyaindia18072026_fsc
sonar.organization=voyaindia18072026
sonar.projectName=FSC
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
